filter:
    paths: [src/*]
    excluded_paths:
        - 'tests/*'
build:
    environment:
        php:
            version: '7.1.0'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit -c tests/phpunit.xml'
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.clover -c tests/phpunit.xml'
                coverage:
                    file: 'coverage.clover'
                    format: 'php-clover'

checks:
    php:
        code_rating: true
        duplication: true

        verify_property_names: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        uppercase_constants: true
        too_many_arguments: true
        symfony_request_injection: true
        spacing_around_non_conditional_operators: true
        spacing_around_conditional_operators: true
        spacing_of_function_arguments: true
        parameter_doc_comments: true
        use_self_instead_of_fqcn: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        remove_extra_empty_lines: true
        phpunit_assertions: true
        param_doc_comment_if_not_inferrable: true
        optional_parameters_at_the_end: true
        no_long_variable_names:
            maximum: '20'
        newline_at_end_of_file: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        avoid_unnecessary_concatenation: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        align_assignments: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
            switch:
                indent_case: false
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
        braces:
            classes_functions:
                class: end-of-line
                function: end-of-line
                closure: end-of-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

